name: jedapus
description: Aplikasi Pengajuan dan Pencatatan Cuti Pegawai

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  supabase_flutter: ^2.3.4
  http: ^1.1.0
  sqflite: ^2.3.0
  path: ^1.8.3
  shimmer: ^3.0.0
  google_fonts: ^6.1.0
  flutter_local_notifications: ^16.3.2
  intl: ^0.19.0
  image_picker: ^1.0.4
  file_picker: ^6.0.0
  lib: ^0.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/